### PR TITLE
Staging/ideaspace

### PR DESCRIPTION
**Pull request by dbradham**
This pull request is to deploy the latest changes from IdeaSpace project

### CODE REVIEW

**Review by Enjoy2Live — CHANGES_REQUESTED** [review]
@dbradham you need to run `yarn install` otherwise the build won't succeed as the deps have changed.

When running it it should make changes to yarn.lock, add those changes to this PR and it should make the build actions pass.

**Comment by dbradham** [comment]
> @dbradham you need to run `yarn install` otherwise the build won't succeed as the deps have changed.
> 
> When running it, it should make changes to yarn.lock, add those changes to this PR and it should make the build actions pass.

Thanks. This should be addressed now, but would be good to have you review again.

**Review by Enjoy2Live — APPROVED** [review]
Looks good to me, congrats on getting closer to a new release!

**Review by RETprojects — APPROVED** [review]
This PR looks good to merge into production. Great job, everyone!

**Pull request merged**
