### PR TITLE
User Card organism

### PR DESCRIPTION
**Pull request by mfvil**
- User card with with vertical and horizontal layout
- added a test image, let me know if needs to be removed

### CODE REVIEW

**Comment by dbradham** [comment]
Hello @mfvil @Enjoy2Live I'm working with the ideas team as TL, I'm wondering if I'm good to use this branch for development?

We may build with this component for the following ticket slotted in our current sprint: https://app.zenhub.com/workspaces/ideaspace-team-6350185d9843157427cc900b/issues/gh/dev-launchers/dev-launchers-platform/787

Thanks,

**Comment by Enjoy2Live** [comment]
> Hello @mfvil @Enjoy2Live I'm working with the ideas team as TL, I'm wondering if I'm good to use this branch for development?
> 
> We may build with this component for the following ticket slotted in our current sprint: https://app.zenhub.com/workspaces/ideaspace-team-6350185d9843157427cc900b/issues/gh/dev-launchers/dev-launchers-platform/787
> 
> Thanks,

I'm going to merge this tonight to master and you guys can make use of it. is there anything else you're blocked by other than expandable blurb and user card?

**Comment by dbradham** [comment]
> > Hello @mfvil @Enjoy2Live I'm working with the ideas team as TL, I'm wondering if I'm good to use this branch for development?
> > We may build with this component for the following ticket slotted in our current sprint: https://app.zenhub.com/workspaces/ideaspace-team-6350185d9843157427cc900b/issues/gh/dev-launchers/dev-launchers-platform/787
> > Thanks,
> 
> I'm going to merge this tonight to master and you guys can make use of it. is there anything else you're blocked by other than expandable blurb and user card?

Thanks!

I don't think we are blocked by anything else, but I will discuss further with Anwar.

**Review by Enjoy2Live — APPROVED** [review]

**Pull request merged**
