### PR TITLE
converting navlinks to tailwind component

### PR DESCRIPTION
**Pull request by yacineKahlerras**

### CODE REVIEW

**Review by chungthuang — APPROVED** [review]

**Comment by chungthuang** [comment]
For my own learning, how did you know we need to transform to ```className="text-grayscale-50 hover:text-blue-200 focus:text-blue-200 active:text-blue-100 active:border-b-[3px] active:text-center active:w-14 active:border-blue-200 active:pb-1 disabled:text-grayscale-600"```? 
If I need to migrate another component, how do I decide what to class to transform to?

**Comment by yacineKahlerras** [comment]
> For my own learning, how did you know we need to transform to `className="text-grayscale-50 hover:text-blue-200 focus:text-blue-200 active:text-blue-100 active:border-b-[3px] active:text-center active:w-14 active:border-blue-200 active:pb-1 disabled:text-grayscale-600"`? If I need to migrate another component, how do I decide what to class to transform to?

just look at the css properties of the styled components and put what the equivalent of that in tailwind classes

**Review by dbradham — APPROVED** [review]
Looks good and cleaner than the original implementation!

**Pull request merged**
