### PR TITLE
Rina/1430 edit profile modal creation blank

### PR DESCRIPTION
**Pull request by rinagobo**
Just created this PR temporarily for me to see my commit records. Not completed this task yet.

### CODE REVIEW

**Comment by rinagobo** [comment]
Hi Jude, 
Could you review my code when you get a chance?

**Comment by rinagobo** [comment]
PR note:
1. Created ProfileEditModal folder containing ProfileEditModal.js, StyledProfileEditModal.js and index.js
2. Created editModalReducer.js in the reducers folder
3. Created UserProfileDataContext.js in the context folder
4. Added <UserProfileDataProvider/> in the _app.js file
5. Added and commented out the code in the BioBox.js for the functionality of opening the ProfileEditModal

**Comment by rinagobo** [comment]
File names updates:
ProfileEditModal.js, StyledProfileEditModal.js  ---> EditProfileModal.js, StyledEditProfileModal.js
editModalReducer.js                                            ---> editProfileReducer.js
UserProfileDataContext.js                                   ---> EditProfileDataContext.js

**Comment by rinagobo** [comment]
Additional Modifications:
1. Created editProfileActions.js in actions folder and used the actions in the file for editProfileReducer.js and EditProfileDataContext.js
2. Created userProfileReducer.js (blank) in reducers folder

**Review by judeamos — APPROVED** [review]
Looks good. Merge when your ready.

**Pull request merged**
