### PR TITLE
fix(design): remove old color tokens

### PR DESCRIPTION
**Pull request by Nouri-Anouar**
Removed outdated colors to prevent duplication and minimize confusion.
We've removed the following colors from our palette, providing updated equivalents for each:

- Light Blue -> Uranus.
- Blue -> Neptune.
- Yellow -> Saturn.
- Orange -> Jupiter.

### CODE REVIEW

**Review by chungthuang — APPROVED** [review]

**Review by Enjoy2Live — APPROVED** [review]
approved, next time make sure your PR destination is development/design-team or directly push to development/design-team. so that the github action that transform tokens from the json file to tailwind classes runs.

thanks for the PR Anwar :rocket:

**Review by wimaan3 — APPROVED** [review]

**Comment by Nouri-Anouar** [comment]
@Enjoy2Live I removed more deprecated colors:
- Notifications
-  Success
- Error 
- Grayscale

Please review and let me know if this is breaking anything.

**Comment by Enjoy2Live** [comment]
@Nouri-Anouar 
I still can see Yellow and Blue and Orange in this PR but you mentioned your goal was to remove them?

Also you removed things [`GreyScale-charcoal`=`#474747` and `GreyScale-grey` = `#7f7e7f`] that were used in switch and pagination, how should we replace them now?
```
./packages/UI/src/components/Switch/Switch.tsx
  57:29  error    Classname 'data-disabled:!bg-GreyScale-charcoal' is not a Tailwind CSS class!  tailwindcss/no-custom-classname

./packages/UI/src/components/Pagination/Pagination.tsx
  48:30  error    Classname 'text-GreyScale-grey' is not a Tailwind CSS class!  tailwindcss/no-custom-classn
```

**Comment by Nouri-Anouar** [comment]
@Enjoy2Live those Yellow, Blue, and Orange colors are those we default TailwindCSS ones. Should we keep them?

As for `GreyScale-charcoal` and `GreyScale-grey`, can we replace both with `grayscale-500`?

**Comment by Enjoy2Live** [comment]
> @Enjoy2Live those Yellow, Blue, and Orange colors are those we default TailwindCSS ones. Should we keep them?
> 

it's up to you whether we should keep them or not, you said you wanted to remove them and I found them so I was just making sure that you didn't overlook it.

> As for `GreyScale-charcoal` and `GreyScale-grey`, can we replace both with `grayscale-500`?
why not!

**Pull request merged**
