### PR TITLE
Development/user profile 1258 fv

### PR DESCRIPTION
**Pull request by sky1122**
image

The image itself is gray, and it will be helpful to change the image color to black to match the model.

### CODE REVIEW

**Review by rinagobo — COMMENTED** [review]
Hi Jingwei,

According to the sample that Ethan gave us, the color of the rocket image should be dark grey. You can use "filter: brightness(0.1)" in css for the image component in order to change the color of the image.

**Comment by Enjoy2Live** [comment]
I got asked to review this, is there a specific thing you want me to review @sky1122? I'm not part of the user-profile team so I'm not so sure how my input will help here, also this PR has been up for too long so I recommend you guys sort it and merge before it becomes harder to!

**Comment by Enjoy2Live** [comment]
@judeamos should we close this PR?

**Comment by judeamos** [comment]
Closing this PR. I've reworked this into another, and have already merged.

**Pull request closed without merging**
