### PR TITLE
feat(design): updates to size, space and font token sets

### PR DESCRIPTION
**Pull request by annaisaacks**
Defines primitive text values:

- font-family
- font-weight
- font-style

### CODE REVIEW

**Comment by dbradham** [comment]
@annaisaacks is this change related to any specific ticket on the universal design board? I am asking so I can confirm these changes have the expected result before we merge to staging

**Comment by annaisaacks** [comment]
@Nouri-Anouar 

Do we have a ticket for adding variables?

**Comment by Nouri-Anouar** [comment]
Hi @dbradham 
Here is a ticket for this PR #2087 

@annaisaacks Please review and lmk if I missed something.

**Review by dbradham — APPROVED** [review]
Approving with the understanding that the tokens file will be transferred to universal design for code ownership moving forward.

**Pull request merged**
