### PR TITLE
feat(footer): add a contact email

### PR DESCRIPTION
**Pull request by Enjoy2Live**

### CODE REVIEW

**Comment by chungthuang** [comment]
Can you share a screenshot of how this will look like?

**Review by chungthuang — APPROVED** [review]

**Comment by zar92** [comment]
I would also like to see how it actually looks like. The contact email should be before Terms of Service.
Screenshot 2024-08-15 184902

**Comment by Enjoy2Live** [comment]
@chungthuang @zar92 
image

**Pull request merged**
