### PR TITLE
Development/user profile

### PR DESCRIPTION
**Pull request by judeamos**
Merged MASTER → development/user-profile branch to fix conflict in `packages/utilities/agent.js`.  
Fixed conflict with @dbradham, as he made some changes to the file. 
@Enjoy2Live  Not sure if you've made any changes to it.
@wimaan3 Can you please check if all our changes is as expected.

### CODE REVIEW

**Comment by Enjoy2Live** [comment]
@judeamos why merge instead of rebase?

**Review by dbradham — APPROVED** [review]

**Comment by judeamos** [comment]
@Enjoy2Live I needed to resolve a conflict within the agent.ts file. In the past, I've had issues with rebasing when resolving file conflicts, so I merge instead. This is a knowledge issue on my part, I'm taking a course on git to get a better understanding. It would be nice to see an example of a branch that has been rebased vs merged... just to see the difference on a code base like this.

**Comment by judeamos** [comment]
All changes are from master branch, nothing has been added. Only modification is in the agent.ts files, since @dbradham has approved, i will be merging in an hours time.

**Comment by judeamos** [comment]
Changes have been merged into `staging/user-profile` branch. 
I have a PR (https://github.com/dev-launchers/dev-launchers-platform/pull/1875) already created to push changes into the master branch. You can review the difference between the master branch and what has been changed in the `agent.ts` file.

**Pull request merged**
