### PR TITLE
Opt-in eslinter for community dev team

### PR DESCRIPTION
**Pull request by alexanderyanthar**
opted into eslinter by following the steps provided through both the documentation and video created by Mohammed and his team

For some reason, I can't automatically merge with the development/new-builds branch even though I pulled my code directly from there. I can automatically merge to master though! Anyway, I'll make a draft pr and we can discuss what to do from there. Thanks!

### CODE REVIEW

**Comment by alexanderyanthar** [comment]
@Enjoy2Live I see. So at some point before you became the tech lead, I re-cloned according to the instructions I was given (from the link that chung ting sent which was to clone the master branch). Then I switched branches to the development/new-builds to pull from which I would proceed to create my own branch. The problem is that there's a bunch of merge conflicts when I try to pull from the development/new-builds as I recall you saying that the new-builds branch is pretty far behind. So at this point, I'm not really sure what to do. It's very possible that I'm missing some step or I haven't done something right and if that's the case I apologize! I haven't touched much of the code for the community platform since probably October/November 2023.

**Comment by Enjoy2Live** [comment]
> @Enjoy2Live I see. So at some point before you became the tech lead, I re-cloned according to the instructions I was given (from the link that chung ting sent which was to clone the master branch). Then I switched branches to the development/new-builds to pull from which I would proceed to create my own branch. The problem is that there's a bunch of merge conflicts when I try to pull from the development/new-builds as I recall you saying that the new-builds branch is pretty far behind. So at this point, I'm not really sure what to do. It's very possible that I'm missing some step or I haven't done something right and if that's the case I apologize! I haven't touched much of the code for the community platform since probably October/November 2023.

No you're actually right, I really appreciate you taking the time to read the docs we made and wanting to keep `development/new-builds` level with `master`.
Unfortunately the previous tech lead didn't do that which made the branch fall behind `master` by dozens of commits and that's the reason why you had a lot of conflicts!

Good news is your changes are in one commit 
[opted into eslinter by following the steps provided through both the …](https://github.com/dev-launchers/dev-launchers-platform/pull/1672/commits/254852bc9ccf714e388633fc223c841cedd367f5)
which means whenever I'm done rebasing `master` to `development/new-builds` we're going to use global eslint config and issue #1626 gets closed.

Thanks a ton @alexanderyanthar :rocket:

**Comment by alexanderyanthar** [comment]
> > @Enjoy2Live I see. So at some point before you became the tech lead, I re-cloned according to the instructions I was given (from the link that chung ting sent which was to clone the master branch). Then I switched branches to the development/new-builds to pull from which I would proceed to create my own branch. The problem is that there's a bunch of merge conflicts when I try to pull from the development/new-builds as I recall you saying that the new-builds branch is pretty far behind. So at this point, I'm not really sure what to do. It's very possible that I'm missing some step or I haven't done something right and if that's the case I apologize! I haven't touched much of the code for the community platform since probably October/November 2023.
> 
> No you're actually right, I really appreciate you taking the time to read the docs we made and wanting to keep `development/new-builds` level with `master`. Unfortunately the previous tech lead didn't do that which made the branch fall behind `master` by dozens of commits and that's the reason why you had a lot of conflicts!
> 
> Good news is your changes are in one commit [opted into eslinter by following the steps provided through both the …](https://github.com/dev-launchers/dev-launchers-platform/pull/1672/commits/254852bc9ccf714e388633fc223c841cedd367f5) which means whenever I'm done rebasing `master` to `development/new-builds` we're going to use global eslint config and issue #1626 gets closed.
> 
> Thanks a ton @alexanderyanthar 🚀

Ahh gotcha! So just to be clear, all I have to do now is wait until you're done rebasing and this task is cleared? I just want to check if there's anything more I need to do :). Speaking of which, if there's anything I can do to help out let me know!

Thanks!

**Comment by Enjoy2Live** [comment]
> > > @Enjoy2Live I see. So at some point before you became the tech lead, I re-cloned according to the instructions I was given (from the link that chung ting sent which was to clone the master branch). Then I switched branches to the development/new-builds to pull from which I would proceed to create my own branch. The problem is that there's a bunch of merge conflicts when I try to pull from the development/new-builds as I recall you saying that the new-builds branch is pretty far behind. So at this point, I'm not really sure what to do. It's very possible that I'm missing some step or I haven't done something right and if that's the case I apologize! I haven't touched much of the code for the community platform since probably October/November 2023.
> > 
> > 
> > No you're actually right, I really appreciate you taking the time to read the docs we made and wanting to keep `development/new-builds` level with `master`. Unfortunately the previous tech lead didn't do that which made the branch fall behind `master` by dozens of commits and that's the reason why you had a lot of conflicts!
> > Good news is your changes are in one commit [opted into eslinter by following the steps provided through both the …](https://github.com/dev-launchers/dev-launchers-platform/pull/1672/commits/254852bc9ccf714e388633fc223c841cedd367f5) which means whenever I'm done rebasing `master` to `development/new-builds` we're going to use global eslint config and issue #1626 gets closed.
> > Thanks a ton @alexanderyanthar 🚀
> 
> Ahh gotcha! So just to be clear, all I have to do now is wait until you're done rebasing and this task is cleared? I just want to check if there's anything more I need to do :). Speaking of which, if there's anything I can do to help out let me know!
> 
> Thanks!

Correct and I'm actually too busy to complete the rebasing, maybe I'll delegate that to you if I take too long as I don't want to block you guys.
we'll see next week!

**Comment by alexanderyanthar** [comment]
> > > > @Enjoy2Live I see. So at some point before you became the tech lead, I re-cloned according to the instructions I was given (from the link that chung ting sent which was to clone the master branch). Then I switched branches to the development/new-builds to pull from which I would proceed to create my own branch. The problem is that there's a bunch of merge conflicts when I try to pull from the development/new-builds as I recall you saying that the new-builds branch is pretty far behind. So at this point, I'm not really sure what to do. It's very possible that I'm missing some step or I haven't done something right and if that's the case I apologize! I haven't touched much of the code for the community platform since probably October/November 2023.
> > > 
> > > 
> > > No you're actually right, I really appreciate you taking the time to read the docs we made and wanting to keep `development/new-builds` level with `master`. Unfortunately the previous tech lead didn't do that which made the branch fall behind `master` by dozens of commits and that's the reason why you had a lot of conflicts!
> > > Good news is your changes are in one commit [opted into eslinter by following the steps provided through both the …](https://github.com/dev-launchers/dev-launchers-platform/pull/1672/commits/254852bc9ccf714e388633fc223c841cedd367f5) which means whenever I'm done rebasing `master` to `development/new-builds` we're going to use global eslint config and issue #1626 gets closed.
> > > Thanks a ton @alexanderyanthar 🚀
> > 
> > 
> > Ahh gotcha! So just to be clear, all I have to do now is wait until you're done rebasing and this task is cleared? I just want to check if there's anything more I need to do :). Speaking of which, if there's anything I can do to help out let me know!
> > Thanks!
> 
> Correct and I'm actually too busy to complete the rebasing, maybe I'll delegate that to you if I take too long as I don't want to block you guys. we'll see next week!

Sounds good! Just let me know whenever :)

**Review by Enjoy2Live — APPROVED** [review]
Finally no more conflicts and we have a new branch called `development/community`

Thanks a lot for implementing this, when we bind this lint-staged there won't be any reason to see commits that only change the code style!

**Pull request merged**
